public class AmazonS3Constants {
    public static final String AMAZON_S3_URL               = '.s3.amazonaws.com';
    public static final String EMPTY_STRING_HASH           = 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855';
    public static final String ENCODING_SCHEME_UTF8        = 'UTF-8';
    public static final String GENERATE_MAC_ALGORITHM_NAME = 'hmacSHA256';
    public static final String HTTP_METHOD_GET             = 'GET';
    public static final String HTTP_METHOD_PUT             = 'PUT';
}